version: '3.7'
services:
  odfe-node1:
    image: amazon/opendistro-for-elasticsearch:1.4.0
    container_name: odfe-node1
    environment:
      - cluster.name=odfe-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - odfe-data1:/usr/share/elasticsearch/data
      # - ./MyRootCA.pem:/usr/share/elasticsearch/config/MyRootCA.pem
      # - ./odfe-node1.pem:/usr/share/elasticsearch/config/odfe-node1.pem
      # - ./odfe-node1.key:/usr/share/elasticsearch/config/odfe-node1.key
      # - ./node1-elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
    networks:
      - odfe-net

  odfe-node2:
    image: amazon/opendistro-for-elasticsearch:1.4.0
    container_name: odfe-node2
    environment:
      - cluster.name=odfe-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.zen.ping.unicast.hosts=odfe-node1
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - odfe-data2:/usr/share/elasticsearch/data
      # - ./MyRootCA.pem:/usr/share/elasticsearch/config/MyRootCA.pem
      # - ./odfe-node2.pem:/usr/share/elasticsearch/config/odfe-node2.pem
      # - ./odfe-node2.key:/usr/share/elasticsearch/config/odfe-node2.key
      # - ./node2-elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - odfe-net

volumes:
  odfe-data1:
  odfe-data2:

networks:
  odfe-net:
